export const specialties = [
  { id: 'Acupuntura', title: 'Acupuntura' },
  { id: 'Alergia e imunologia', title: 'Alergia e imunologia' },
  { id: 'Anestesiologia', title: 'Anestesiologia' },
  { id: 'Angiologia', title: 'Angiologia' },
  { id: 'Cardiologia', title: 'Cardiologia' },
  { id: 'Cirurgia cardiovascular', title: 'Cirurgia cardiovascular' },
  { id: 'Cirurgia da mão', title: 'Cirurgia da mão' },
  { id: 'Cirurgia de cabeça e pescoço', title: 'Cirurgia de cabeça e pescoço' },
  { id: 'Cirurgia do aparelho digestivo', title: 'Cirurgia do aparelho digestivo' },
  { id: 'Cirurgia geral', title: 'Cirurgia geral' },
  { id: 'Cirurgia oncológica', title: 'Cirurgia oncológica' },
  { id: 'Cirurgia pediátrica', title: 'Cirurgia pediátrica' },
  { id: 'Cirurgia plástica', title: 'Cirurgia plástica' },
  { id: 'Cirurgia torácica', title: 'Cirurgia torácica' },
  { id: 'Cirurgia vascular', title: 'Cirurgia vascular' },
  { id: 'Clínica médica', title: 'Clínica médica' },
  { id: 'Coloproctologia', title: 'Coloproctologia' },
  { id: 'Dermatologia', title: 'Dermatologia' },
  { id: 'Endocrinologia e metabologia', title: 'Endocrinologia e metabologia' },
  { id: 'Gastroenterologia', title: 'Gastroenterologia' },
  { id: 'Genética médica', title: 'Genética médica' },
  { id: 'Ginecologia e obstetrícia', title: 'Ginecologia e obstetrícia' },
  { id: 'Hematologia e hemoterapia', title: 'Hematologia e hemoterapia' },
  { id: 'Homeopatia', title: 'Homeopatia' },
  { id: 'Infectologia', title: 'Infectologia' },
  { id: 'Mastologia', title: 'Mastologia' },
  { id: 'Medicina de emergência', title: 'Medicina de emergência' },
  { id: 'Medicina de família e comunidade', title: 'Medicina de família e comunidade' },
  { id: 'Medicina do trabalho', title: 'Medicina do trabalho' },
  { id: 'Medicina de tráfego', title: 'Medicina de tráfego' },
  { id: 'Medicina esportiva', title: 'Medicina esportiva' },
  { id: 'Medicina física e reabilitação', title: 'Medicina física e reabilitação' },
  { id: 'Medicina intensiva', title: 'Medicina intensiva' },
  { id: 'Medicina legal e perícia médica', title: 'Medicina legal e perícia médica' },
  { id: 'Medicina nuclear', title: 'Medicina nuclear' },
  { id: 'Medicina preventiva e social', title: 'Medicina preventiva e social' },
  { id: 'Médico examinador', title: 'Médico examinador' },
  { id: 'Nefrologia', title: 'Nefrologia' },
  { id: 'Neurocirurgia', title: 'Neurocirurgia' },
  { id: 'Neurologia', title: 'Neurologia' },
  { id: 'Nutrologia', title: 'Nutrologia' },
  { id: 'Oftalmologia', title: 'Oftalmologia' },
  { id: 'Oncologia clínica', title: 'Oncologia clínica' },
  { id: 'Ortopedia e traumatologia', title: 'Ortopedia e traumatologia' },
  { id: 'Otorrinolaringologia', title: 'Otorrinolaringologia' },
  { id: 'Patologia', title: 'Patologia' },
  { id: 'Patologia clínica/medicina laboratorial', title: 'Patologia clínica/medicina laboratorial' },
  { id: 'Pediatria', title: 'Pediatria' },
  { id: 'Pneumologia', title: 'Pneumologia' },
  { id: 'Psiquiatria', title: 'Psiquiatria' },
  { id: 'Radiologia e diagnóstico por imagem', title: 'Radiologia e diagnóstico por imagem' },
  { id: 'Radioterapia', title: 'Radioterapia' },
  { id: 'Reumatologia', title: 'Reumatologia' },
  { id: 'Urologia', title: 'Urologia' },
]

export const categories = [
  { id: 'Estado', title: 'Estado' },
  { id: 'Região', title: 'Região' },
  { id: 'Especialidade', title: 'Especialidade' },
  { id: 'Outro', title: 'Outro' },
]